version: '3'

services:
  app:
    build:
      context: .
    image: sqlalchemy-docker-app
    command: python -m flask run
    environment:
      - FLASK_APP=main.py
    volumes:
      - ./app:/app
    ports:
      - 5000:5000
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql/initdb:/docker-entrypoint-initdb.d
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo

